# TravisCI config for circuitpython.org

# only run if triggered by a cron
if: type = cron

dist: xenial
language: python
python: "3.6"

install:
  - pip install -r adabot/requirements.txt

addons:
  artifacts:
    paths:
    - $HOME/web/libraries.json
    target_paths: /adabot
    debug: true

script:
  - mkdir -p $HOME/web
  - cd adabot
  - python -u -m adabot.update_cp_org_libraries -o $HOME/web/libraries.json
