title: CircuitPython
email: justin@adafruit.com
description: >-
  CircuitPython Organization
timezone: America/New_York
twitter_username: adafruit
github_username:  adafruit
paginate: 5
excerpt_separator: <!--more-->
permalink: pretty
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-get-json
  - jekyll-redirect-from
# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# Sass settings
sass:
  add_charset: true
  sass_dir: assets/sass
style: :compressed

# Collections
collections:
  board:
    output: true
  blinka:
    output: true

jekyll_get_json:
  - data: libraries
    json: 'https://adafruit-circuit-python.s3.amazonaws.com/adabot/web/libraries.v2.json'

### Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _src
  - _images
  - LICENSE
  - package.json
  - README.md
  - webpack.config.js
  - yarn-error.log
  - yarn.lock
  - config
  - optimization-fix
  - optimization-fix-this-file-is-ignored.js
  - icon.png
  - template.md
  - Rakefile
